"""add master_resume and resume_block

Revision ID: 3a028dae3f9e
Revises: a380bc937d8a
Create Date: 2026-08-03 05:22:54.750665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '3a028dae3f9e'
down_revision: Union[str, Sequence[str], None] = 'a380bc937d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_resume_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['master_resume_id'], ['master_resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_block')
    op.drop_table('master_resume')
    # ### end Alembic commands ###
