"""add job_posting.queue_status

Revision ID: 3e57b108605b
Revises: 78b0d2535a6a
Create Date: 2026-08-05 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '3e57b108605b'
down_revision: Union[str, Sequence[str], None] = '78b0d2535a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The Discover-queue triage state (new/saved/dismissed). A server_default of
    # 'new' backfills every existing posting so the NOT NULL column is valid
    # without a data migration; new inserts get the same default from the model.
    op.add_column(
        'job_posting',
        sa.Column(
            'queue_status',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='new',
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('job_posting', 'queue_status')
