"""add cover_letter

Revision ID: 78b0d2535a6a
Revises: 4254054ad3ef
Create Date: 2026-08-04 06:14:54.206968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '78b0d2535a6a'
down_revision: Union[str, Sequence[str], None] = '4254054ad3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rendered_pdf_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cover_letter')
    # ### end Alembic commands ###
