"""add score_claim

Revision ID: 7f2a9c4d1e60
Revises: 3e57b108605b
Create Date: 2026-08-05 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '7f2a9c4d1e60'
down_revision: Union[str, Sequence[str], None] = '3e57b108605b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The scoring-lease table (PROJECT.md §4.1 "owned by" convention): one row per
    # (posting, profile) pair being scored, unique so a stray second writer can't
    # double-claim.
    op.create_table(
        'score_claim',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_posting_id', sa.Integer(), nullable=False),
        sa.Column('profile_id', sa.Integer(), nullable=False),
        sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('claimed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], ),
        sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('job_posting_id', 'profile_id', name='uq_score_claim_pair'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('score_claim')
